package sjpp;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Unit tests for the {@link JavaFile} class - remove file directive.
 * 
 * Tests that when a file is marked for removal with {@code //::remove file when __FLAG__},
 * the file is excluded from output AND all import statements referencing this file
 * in other files are also removed.
 */
class JavaFileRemoveFileTest {

    @TempDir
    Path tempDir;

    @Test
    void removeFile_shouldExcludeFileFromOutput_whenFlagIsActive() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        String removedFileContent = """
                package com.example;

                //::remove file when __TEST__

                public class ToBeRemoved {
                    public void doSomething() {
                    }
                }
                """;

        Path removedFile = packageDir.resolve("ToBeRemoved.java");
        Files.writeString(removedFile, removedFileContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act
        JavaFile javaFile = new JavaFile(context, removedFile);

        // Assert - the file should be registered as removed in the context
        assertTrue(context.removeImportLine("com.example.ToBeRemoved"),
                "The file should be marked as removed in the context");
    }

    @Test
    void removeFile_shouldNotExcludeFile_whenFlagIsNotActive() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        String fileContent = """
                package com.example;

                //::remove file when __OTHER_FLAG__

                public class NotRemoved {
                    public void doSomething() {
                    }
                }
                """;

        Path javaFilePath = packageDir.resolve("NotRemoved.java");
        Files.writeString(javaFilePath, fileContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act
        JavaFile javaFile = new JavaFile(context, javaFilePath);

        // Assert - the file should NOT be marked as removed
        assertFalse(context.removeImportLine("com.example.NotRemoved"),
                "The file should NOT be marked as removed when flag doesn't match");
    }

    @Test
    void removeFile_shouldRemoveImportInOtherFile_whenFileIsRemoved() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        // File that will be removed
        String removedFileContent = """
                package com.example;

                //::remove file when __TEST__

                public class HelperClass {
                    public static void help() {
                    }
                }
                """;

        // File that imports the removed file
        String mainFileContent = """
                package com.example;

                import com.example.HelperClass;
                import java.util.List;

                public class MainClass {
                    public void method() {
                        System.out.println("Hello");
                    }
                }
                """;

        String expectedMainFileOutput = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                import java.util.List;

                public class MainClass {
                    public void method() {
                        System.out.println("Hello");
                    }
                }
                """;

        Path removedFile = packageDir.resolve("HelperClass.java");
        Path mainFile = packageDir.resolve("MainClass.java");
        Files.writeString(removedFile, removedFileContent);
        Files.writeString(mainFile, mainFileContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act - load both files (order matters: removed file first to register it)
        JavaFile helperJavaFile = new JavaFile(context, removedFile);
        JavaFile mainJavaFile = new JavaFile(context, mainFile);

        mainJavaFile.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("MainClass.java");
        mainJavaFile.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expectedMainFileOutput), normalizeLineEndings(result),
                "The import of the removed file should be removed from the output");
    }

    @Test
    void removeFile_shouldRemoveMultipleImports_whenMultipleFilesAreRemoved() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Path utilDir = tempDir.resolve("com/util");
        Files.createDirectories(packageDir);
        Files.createDirectories(utilDir);

        // First file to be removed
        String helperContent = """
                package com.example;

                //::remove file when __TEST__

                public class Helper {
                }
                """;

        // Second file to be removed
        String utilityContent = """
                package com.util;

                //::remove file when __TEST__

                public class Utility {
                }
                """;

        // File that imports both removed files
        String mainContent = """
                package com.example;

                import com.example.Helper;
                import com.util.Utility;
                import java.util.ArrayList;

                public class Main {
                }
                """;

        String expectedOutput = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                import java.util.ArrayList;

                public class Main {
                }
                """;

        Path helperFile = packageDir.resolve("Helper.java");
        Path utilityFile = utilDir.resolve("Utility.java");
        Path mainFile = packageDir.resolve("Main.java");
        
        Files.writeString(helperFile, helperContent);
        Files.writeString(utilityFile, utilityContent);
        Files.writeString(mainFile, mainContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act - load all files (removed files first)
        new JavaFile(context, helperFile);
        new JavaFile(context, utilityFile);
        JavaFile mainJavaFile = new JavaFile(context, mainFile);

        mainJavaFile.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("Main.java");
        mainJavaFile.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expectedOutput), normalizeLineEndings(result),
                "All imports of removed files should be removed");
    }

    @Test
    void removeFile_shouldCommentImportInDebugMode_whenFileIsRemoved() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        String removedFileContent = """
                package com.example;

                //::remove file when __TEST__

                public class RemovedClass {
                }
                """;

        String mainFileContent = """
                package com.example;

                import com.example.RemovedClass;

                public class MainClass {
                }
                """;

        String expectedOutput = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                // import com.example.RemovedClass;

                public class MainClass {
                }
                """;

        Path removedFile = packageDir.resolve("RemovedClass.java");
        Path mainFile = packageDir.resolve("MainClass.java");
        Files.writeString(removedFile, removedFileContent);
        Files.writeString(mainFile, mainFileContent);

        Context context = new Context(ContextMode.DEBUG, tempDir);
        context.addDefine("__TEST__");

        // Act
        new JavaFile(context, removedFile);
        JavaFile mainJavaFile = new JavaFile(context, mainFile);

        mainJavaFile.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("MainClass.java");
        mainJavaFile.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expectedOutput), normalizeLineEndings(result),
                "In DEBUG mode, the import should be commented out instead of removed");
    }

    @Test
    void removeFile_shouldKeepImport_whenImportedFileNotRemoved() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        String keepFileContent = """
                package com.example;

                public class KeptClass {
                }
                """;

        String mainFileContent = """
                package com.example;

                import com.example.KeptClass;

                public class MainClass {
                }
                """;

        String expectedOutput = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                import com.example.KeptClass;

                public class MainClass {
                }
                """;

        Path keptFile = packageDir.resolve("KeptClass.java");
        Path mainFile = packageDir.resolve("MainClass.java");
        Files.writeString(keptFile, keepFileContent);
        Files.writeString(mainFile, mainFileContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act
        new JavaFile(context, keptFile);
        JavaFile mainJavaFile = new JavaFile(context, mainFile);

        mainJavaFile.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("MainClass.java");
        mainJavaFile.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expectedOutput), normalizeLineEndings(result),
                "Imports of non-removed files should be kept");
    }

    @Test
    void removeFile_shouldHandleStaticImport_whenFileIsRemoved() throws IOException {
        // Arrange
        Path packageDir = tempDir.resolve("com/example");
        Files.createDirectories(packageDir);

        String removedFileContent = """
                package com.example;

                //::remove file when __TEST__

                public class Constants {
                    public static final int VALUE = 42;
                }
                """;

        String mainFileContent = """
                package com.example;

                import static com.example.Constants.VALUE;
                import java.util.List;

                public class MainClass {
                }
                """;

        String expectedOutput = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                import java.util.List;

                public class MainClass {
                }
                """;

        Path removedFile = packageDir.resolve("Constants.java");
        Path mainFile = packageDir.resolve("MainClass.java");
        Files.writeString(removedFile, removedFileContent);
        Files.writeString(mainFile, mainFileContent);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act
        new JavaFile(context, removedFile);
        JavaFile mainJavaFile = new JavaFile(context, mainFile);

        mainJavaFile.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("MainClass.java");
        mainJavaFile.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expectedOutput), normalizeLineEndings(result),
                "Static imports of removed files should also be removed");
    }

    private String normalizeLineEndings(String s) {
        return s.replace("\r\n", "\n").stripTrailing();
    }

}
