package sjpp;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Unit tests for the {@link JavaFile} class.
 */
class JavaFileCommentTest {

    @TempDir
    Path tempDir;

    @Test
    void process_shouldRemoveLinesInsideCommentBlock_whenFlagIsActive() throws IOException {
        // Arrange
        String input = """
                package com.example;

                public class Sample {
                    public void method() {
                        System.out.println("before");
                        //::comment when __TEST__
                        System.out.println("this should be removed");
                        System.out.println("this too");
                        //::done
                        System.out.println("after");
                    }
                }
                """;

        String expected = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                public class Sample {
                    public void method() {
                        System.out.println("before");
                        System.out.println("after");
                    }
                }
                """;

        Path javaFile = tempDir.resolve("Sample.java");
        Files.writeString(javaFile, input);

        Context context = new Context(ContextMode.REGULAR, tempDir);
        context.addDefine("__TEST__");

        // Act
        JavaFile file = new JavaFile(context, javaFile);
        file.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("Sample.java");
        file.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expected), normalizeLineEndings(result));
    }

    @Test
    void process_shouldCommentLinesInsideCommentBlock_whenDebugMode() throws IOException {
        // Arrange
        String input = """
                package com.example;

                public class Sample {
                    public void method() {
                        System.out.println("before");
                        //::comment when __TEST__
                        System.out.println("this should be commented");
                        System.out.println("this too");
                        //::done
                        System.out.println("after");
                    }
                }
                """;

        String expected = """
                // THIS FILE HAS BEEN GENERATED BY A PREPROCESSOR.
                package com.example;

                public class Sample {
                    public void method() {
                        System.out.println("before");
                        //::comment when __TEST__
                //         System.out.println("this should be commented");
                //         System.out.println("this too");
                        //::done
                        System.out.println("after");
                    }
                }
                """;

        Path javaFile = tempDir.resolve("Sample.java");
        Files.writeString(javaFile, input);

        Context context = new Context(ContextMode.DEBUG, tempDir);
        context.addDefine("__TEST__");

        // Act
        JavaFile file = new JavaFile(context, javaFile);
        file.process();

        Path outputDir = tempDir.resolve("output");
        Path outputFile = outputDir.resolve("Sample.java");
        file.save(outputFile);

        // Assert
        String result = Files.readString(outputFile);
        assertEquals(normalizeLineEndings(expected), normalizeLineEndings(result));
    }

    private String normalizeLineEndings(String s) {
        return s.replace("\r\n", "\n").stripTrailing();
    }

}
